name: Detect breaking changes

on: push

jobs:
  build:
    name: Detecting breaking changes
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: c-hive/gha-yarn-cache@v2

    - name: Yarn install
      run: yarn install --immutable

    - name: Build packages
      run: yarn packages:build 

    - name: Detect breaking changes
      run: ./scripts/check-breaking-changes.sh 

    - uses: jwalton/gh-find-current-pr@v1
      id: finder

    - name: Comment on PR
      if: ${{ env.BREAKING_CHANGES_IS_BREAKING == '1' || env.BREAKING_CHANGES_IS_BREAKING == 1 }}
      uses: marocchino/sticky-pull-request-comment@v2
      with:
        number: ${{ steps.finder.outputs.pr }}
        message: |
          **Possible breaking changes**

          ${{ env.BREAKING_CHANGES_MESSAGE }}

          [More info](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})

    - name: Exit
      run: exit ${{ env.BREAKING_CHANGES_IS_BREAKING }}
      shell: bash

